-name: install nginx
 hosts: web
 became: yes
 tasks:
 - name: nginx install
   ansible.builtin.package:
     name: nginx
     state: present

 - name: start nginx
   ansible.builtin.package:
     name: nginx
     state: started
     enabled: yes
 