- name: prompt level
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: "the course name is  "
  - name: DURATION
    prompt: "the duartion is  "
  - name: TRAINER
    prompt: "the trainer is "
  tasks:
  - name: prompt variables
    ansible.builtin.debug:
      msg: "hey, i am learning {{COURSE}}, duration is {{DURATION}},trainer is {{TRAINER}}"

    