name: create user
hosts: web
become: yes
tasks:
- name: check the user
  ansible.builtin.command: id expense
  register: USER
  ignore_errors: true

- name: print the user
  ansible.builtin.debug: 
    msg: " {{USER}} created"

- name: create the user if not exists
  ansible.builtin.command: useradd expense
  when: USER.rc != 0
  