- name: create ec2 instance
  hosts: local
  connection: local
  vars:
    var-file.yaml
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9  
  - name: creating server
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t2.micro"
      vpc_subnet_id: "{{SUB_ID}}"
      security_group: "{{SEC_ID}}"
      image_id: "{{AMI_ID}}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "print the {{ec2_instances}}"

  - name: creating private route53 records
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"

  - name: creating public route53 recors
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{zone}}"
      type: A
      value: "{{item.instances[0].public_ip_address}}"
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
    when: item.item == "frontend"
      