- name: create ec2 instance
  hosts: local
  connection: local
  vars:
    SUB_ID: "subnet-05638ab9ab29014df"
    SEC_ID: "sg-0a8859b9d9e25585f"
    AMI_ID: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: "sujithyerra.online"
  tasks:
  - name: creating server
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t2.micro"
      vpc_subnet_id: "{{SUB_ID}}"
      security_group: "{{SEC_ID}}"
      image_id: "{{AMI_ID}}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "print the {{ec2_instances}}"

  - name: creating private route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ZONE}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
      loop: "{{ec2_instances.results}}"

  - name: creating public route53 recors
    amazon.aws.route53:
      state: present
      zone: "{{ZONE}}"
      record: "{{ZONE}}"
      type: A
      value: "{{item.instances[0].public_ip_address}}"
      ttl: 1
      wait: true
      overwrite: true
      loop: "{{ec2_instances.results}}"
      when: item.item == "frontend"
      